Fix flaky service instance delete e2e test
cloudfoundry/cf-k8s-controllers pull request #860
Opened 2022-03-24 23:17 UTC by clintyoshimura

## Is there a related GitHub Issue?
No

## What is this change about?
Fix service instance delete e2e test to use eventually to reduce the number of flakes

## Does this PR introduce a breaking change?

No

## Acceptance Steps

The e2e service instance delete test passes consistently

## Tag your pair, your PM, and/or team

@matt-royal

2022-03-24 23:18 UTC, matt-royal approved these changes
LGTM

2022-03-25 11:03 UTC, kieron-dev requested changes
Fine apart from the `FWhen`

2022-03-25 11:03 UTC, kieron-dev commented on api/tests/e2e/service_instances_test.go
> +		FWhen("the user has permissions to delete service instances", func() {
Better remove this focus!

2022-03-25 21:50 UTC, tcdowney approved these changes
LGTM

2022-03-28 08:36 UTC, kieron-dev approved these changes

2022-03-28 08:36 UTC, merged